export const jobTitleSelectors = [
  "h1",
  "h2",
  "h3",
  ".job-title",
  ".title",
  ".posting-title",
  ".position-title",
  ".job-header-title",
  "#jobTitle",
  "#positionTitle",
  '[class*="title"]',
  '[id*="title"]',
  '[class*="position"]',
];

export const jobDescriptionSelectors = [
  ".job-description > p",
  ".description > p",
  ".responsibilities",
  "section:contains('Job Description')",
  "section:contains('Description')",
  "p:contains('Job Description')",
  "p:contains('Description')",
  ".job-description",
  ".description",
  ".job-desc",
  ".job-details",
  ".job-content",
  ".job-body",
  ".posting-description",
  ".job-description-content",
  '[class*="description"]',
  '[class*="details"]',
  '[class*="content"]',
  'section:contains("Job Description")',
  'section:contains("Responsibilities")',
  'div:contains("Job Overview")',
  'p:contains("Job Description")',
  'p:contains("Responsibilities")',
  'div:contains("Requirements")',
  "article",
  "section",
  "div",
];

export const companyNameSelectors = [
  ".company",
  ".employer",
  ".company-name",
  ".companyHeader",
  ".posting-company",
  ".job-company",
  ".job-header-company",
  "#companyName",
  "#company-header",
  "#jobCompany",
  '[class*="company"]',
  '[id*="company"]',
  "[data-company]",
  ".job-metadata .employer",
  ".job-company .company-name",
];
